### ISSUE TITLE
Test Failures

### ISSUE THREAD

**Issue by svenefftinge** [crapo/sadlos2#127]
In sadl there are 7 tests failing for me.
@crapo Could you have a look?

**Comment by svenefftinge** [comment]
<img width="462" alt="screen shot 2016-11-16 at 10 15 20" src="https://cloud.githubusercontent.com/assets/372735/20341445/89aed6c6-abe6-11e6-87e9-1077cf168e84.png">

**Comment by crapo** [comment]
There are still 2 failures in SadlModelProcessorTestAmbiguousNames. These seem to be because ambiguous names are not being detected. There is this class to control checking, parallel to the preference for checking in the IDE, but the solution doesn't seem to be as simple as always checking (setting ambiguousNameDetection true in SADLScopeProvider. So not sure where the problem lies...

Likewise with the 4 tests in ExternalEmfResourcesTest. I'm not sure what has changed that makes these fail.

**Comment by kittaakos** [comment]
I have fixed all failing tests but the `SadlModelProcessorTestAmbiguousNames.testAmbiguousDetection()` one. I would need some domain specific clarification before I could proceed with this task.

Let assume the following models:
```
uri "http://sadl.org/Foo.sadl" alias Foo.

C is a class.
```

```
uri "http://sadl.org/Bar.sadl" alias Bar.

C is a class.
```

```
uri "http://sadl.org/Test.sadl".

import "http://sadl.org/Foo.sadl".
import "http://sadl.org/Bar.sadl".

Test is a C.
```

In this case, I can understand why the validation error complaining about the ambiguous import names is required. Since we cannot decide which `C` we are referencing in the `Test` resource, it is a right test case with the proper assertion.


However, the (stripped down version) of the still failing test case uses the following models:

```
uri "http://sadl.org/Foo.sadl" alias Foo.

C is a class.
```

```
uri "http://sadl.org/Bar.sadl" alias Bar.

import "http://sadl.org/Foo.sadl".
```

```
uri "http://sadl.org/Test.sadl".

import "http://sadl.org/Foo.sadl".
import "http://sadl.org/Bar.sadl".

Test is a C.
```

Although `C` is available in `Test` from `Bar` via the imported `Foo` and directly from `Foo` it is not ambiguous because it is exactly the same `C` instance, hence no validation errors should be reported, right? Otherwise, the following case would not work either.

 - `Base` resource declares and exports `B`.
 - `Sub1` resource imports `Base`, declares nothing but transitively re-exports `B` from `Base`.
 - `Sub2` resource imports `Base`, declares nothing but transitively re-exports `B` from `Base`.
 - `Leaf` resource imports `Sub1` and `Sub2` and imports implicitly `B` from `Base` via both `Sub1` and `Sub2`.

This case is valid because we are talking about exactly the same `B`. Is that correct?

Could you please double check, if [the failing test case] has to fail? In other words, does the assertion correct?

[the failing test case]: https://github.com/crapo/sadlos2/blob/master/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/model/SadlModelProcessorTestAmbiguousNames.xtend#L72

**Comment by crapo** [comment]
You are correct. Where as the first case with two definitions of C the reference is ambiguous, in the stripped down case there is no ambiguity. My recollection is that these tests are failing for some reason that seems to be independent of any real ambiguity. I could not easily understand why.

**Comment by kittaakos** [comment]
Great, thanks for the clarification. I will update the test assertions. The updated test statements will be part of the pull request I will open soon. So you do not have to do anything.

**Comment by kittaakos** [comment]
This ticket can be resolved as fixed once the [xtext_web_prototype] branch is merged to master.

[xtext_web_prototype]: https://github.com/crapo/sadlos2/tree/xtext_web_prototype

**Comment by kittaakos** [comment]
The web prototype changes have been merged to the master branch. I close this ticket.
