### ISSUE TITLE
Find SadlResource of Named Query

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#219]
Would like to be able to find the SadlResource of a Named Query  in the current SadlModel or an imported SadlModel (directly or indirectly imported). The code location in the sadl.ui is com.ge.research.sadl.ui.handlers.RunQuery.java, like 187. The current code tries to find the query in the OWL models using the query name (currentQuery). It would be preferable to find the SadlResource with that name (currentQuery), get it's declaration, and get the query body to translate from the declaration.

**Comment by kittaakos** [comment]
@crapo, instead of modifying the `RunQuery` class, I have added a very simple helper service that retrieves the query statement from a Xtext resource by its name. I have also added a couple of tests to make sure that the prefix name matching works as you would expect. The corresponding PR is [here](https://github.com/crapo/sadlos2/pull/222).

**Comment by kittaakos** [comment]
Merged via #222.
