### ISSUE TITLE
Broken quick fixes for ambiguous name validation issues

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#271]

**Comment by kittaakos** [comment]
According to the current state of the code, we offer two alternatives. This is more than nothing but does not cover all the cases. Let assume the followings:

`T1.sadl`:
```
uri "http://sadl.org/T1.sadl" alias T1.
Foo is a class.
```

`T2.sadl`:
```
uri "http://sadl.org/T2.sadl" alias T2.
Foo is a class.
```

`Current.sadl`:
```
uri "http://sadl.org/Current.sadl" alias current.
import "http://sadl.org/T1.sadl".
import "http://sadl.org/T2.sadl".

current:Foo is a class.
Baz is a type of <Foo>.
```

We have a validation error at `<Foo>` which is correct, but instead of proposing 2 possible alternatives we should propose three: `T1:Foo`, `T2:Foo` and `current:Foo`.

Also, we have to take into consideration the following: `T1` model does not have an alias but imported as `TImported`, then we have to propose `TImported:Foo`, `T2:Foo` and `current:Foo`.

To properly support all the use-cases I have mentioned, we need to adjust the scope provider.

**Comment by kittaakos** [comment]
Furthermore, the import could come from more than two models, so it is obviously not just two alternatives.

**Comment by crapo** [comment]
I agree with your analysis of possible alternatives. 
We could easily make an alias in the "uri" statement required instead of just a warning if absent, but there would still be the case of OWL files with no global alias (although the external model URL list editor could require input of such). However, here we are not in alignment with possibilities as an OWL model might have multiple namespaces in it. We do not handle that case.

I'm missing how big an effort is involved...
