### ISSUE TITLE
Add frontend contribution to run SADL/SPARQL queries

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#305]
This requires an input message dialog.

**Comment by kittaakos** [comment]
First, I need to figure out what does the current (Eclipse-based dialog) logic supposed to do.

<img width="545" alt="screen shot 2018-05-10 at 15 56 00" src="https://user-images.githubusercontent.com/1405703/39873247-aabe355e-546a-11e8-8ea2-1a54cfab6460.png">


<img width="274" alt="screen shot 2018-05-10 at 15 51 47" src="https://user-images.githubusercontent.com/1405703/39873185-81eb1390-546a-11e8-8feb-d70690b02a9c.png">


https://github.com/crapo/sadlos2/commit/0f5cd506261b8501bfe9d20278a75fd295dd28f5

**Comment by crapo** [comment]
It's just to allow the user to enter an adhoc query. It could be in SADL grammar or SPARQL grammar, the processor will guess which. The Eclipse implementation also saves queries in the configuration.rdf file and makes them available as a dropdown list so that queries can easily be repeated without having to type or paste them in again.

**Comment by kittaakos** [comment]
Thank you for the prompt reply! Great, I will simplify the current logic a bit.

**Comment by kittaakos** [comment]
> I will simplify the current logic a bit.

That was unnecessary. The `query` argument will be passed to the core implementation as a string. The current Eclipse-approach remains the same.

For the Theia part; we need a simple text input dialog.

**Comment by crapo** [comment]
Project: [Test.zip](https://github.com/crapo/sadlos2/files/2005612/Test.zip)
Use the queries in test.sadl. When the model is run, all of the queries should return values. With timing turned on, the results look like this:
  *************************** start test model output **************************
Inference of '/TestSadl3Ide/Shapes/Test.sadl' requested.
Query: select ?v0 ?v1 where {?v0 <http://sadl.org/Shapes.sadl#area> ?v1}
     v0, v1
     http://sadl.org/Shapes.sadl#MyCircle, 28.27433466911316
     http://sadl.org/Test.sadl#MyRect, 8.0
Timing info:
   32 ms: LoadModelTime, load ontology model
   31 ms: LoadRulesTime, load model 2 rules
   0 ms: LoadRulesTime, bind schema to reasoner
   15 ms: PrepareQuery, prepare query (select ?v0 ?v1 where {?v0 <http://sadl.org/Shapes.sadl#area> ?v1})
   94 ms: PrepareInfModelTime, prepare inference model
   109 ms: ExecuteQueryTime, execute query (select ?v0 ?v1 where {?v0 <http://sadl.org/Shapes.sadl#area> ?v1})

Query: select ?v2 ?v3 where {?v2 <http://sadl.org/Shapes.sadl#area> ?v3}
     v2, v3
     http://sadl.org/Shapes.sadl#MyCircle, 28.27433466911316
     http://sadl.org/Test.sadl#MyRect, 8.0
Timing info:
   0 ms: PrepareQuery, prepare query (select ?v2 ?v3 where {?v2 <http://sadl.org/Shapes.sadl#area> ?v3})
   1 ms: ExecuteQueryTime, execute query (select ?v2 ?v3 where {?v2 <http://sadl.org/Shapes.sadl#area> ?v3})

Query: select ?v4 where {<http://sadl.org/Shapes.sadl#MyCircle> <http://sadl.org/Shapes.sadl#area> ?v4}
     v4 = 28.27433466911316
Timing info:
   0 ms: PrepareQuery, prepare query (select ?v4 where {<http://sadl.org/Shapes.sadl#MyCircle> <http://sadl.org/Shapes.sadl#area> ?v4})
   0 ms: ExecuteQueryTime, execute query (select ?v4 where {<http://sadl.org/Shapes.sadl#MyCircle> <http://sadl.org/Shapes.sadl#area> ?v4})

Query: select ?x where {?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sadl.org/sadlimplicitmodel#Rule>}
     x
     http://sadl.org/Polygons.sadl#AreaOfRectangle
     http://sadl.org/Shapes.sadl#AreaOfCircle
Timing info:
   0 ms: PrepareQuery, prepare query (select ?x where {?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sadl.org/sadlimplicitmodel#Rule>})
   0 ms: ExecuteQueryTime, execute query (select ?x where {?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sadl.org/sadlimplicitmodel#Rule>})

Query: select ?s where {?s <rdf:type> <Shape>}
     s
     http://sadl.org/Shapes.sadl#MyCircle
     http://sadl.org/Test.sadl#MyRect
Timing info:
   0 ms: PrepareQuery, prepare query (select ?s where {?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sadl.org/Shapes.sadl#Shape>})
   0 ms: ExecuteQueryTime, execute query (select ?s where {?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sadl.org/Shapes.sadl#Shape>})

Query: select ?s ?a where {?s <area> ?a}
     s, a
     http://sadl.org/Shapes.sadl#MyCircle, 28.27433466911316
     http://sadl.org/Test.sadl#MyRect, 8.0
Timing info:
   0 ms: PrepareQuery, prepare query (select ?s ?a where {?s <http://sadl.org/Shapes.sadl#area> ?a})
   0 ms: ExecuteQueryTime, execute query (select ?s ?a where {?s <http://sadl.org/Shapes.sadl#area> ?a})
  *************************** end test model output **************************

Not all of these queries will currently work from "Run Query". The following work or should work when put in as ad hoc query:
1) Q1      (works)
2) Shapes:Q1  (this should work but there is a bug in the code to find by name that doesn't support QName)
3) select ?s where {?s <rdf:type> <Shape>}      (works)
4) select ?s ?a where {?s <area> ?a}       (works)

The other queries don't work because there is not the correct processing of an ad hoc query for their form.

**Comment by kittaakos** [comment]
It is supported with one single exception: we do not store previous queries for the web. So the user cannot reuse them.
