### ISSUE TITLE
Index external models

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#37]
When external OWL files are added to a project, the Resource as well as [selected] concepts in the resource need to be added to the index and made available for import into and use in SADL models.

**Comment by GEGlobalResearch** [comment]
This is becoming more clear now. There are concepts in OWL that are generated from the grammar, i.e., List, Equation, External. These translate into OWL concepts that need to be imported by the OWL files generated, but these concepts are never referenced by their OWL concept name because they are built into the grammar.
Then there are implicit  OWL concepts that are generated from the grammar but also may need to be used as concepts in the SADL model, i.e., UnitedQuantity and its properties. This OWL model will need to be indexed and imported implicitly. Hence this external model indexing will be needed for this concepts to work.

**Comment by GEGlobalResearch** [comment]
Here is a simple model:
 uri "http://sadl.org/test.sadl" alias test.

Thingy is a class, described by attribute1 with values of type int,
	described by relation1 with values of type Thingy.

MyThingy is a Thingy with attribute1 23, with relation1 OtherThingy.
OtherThingy is a Thingy.

Attached is a zip file containing the .owl, .n3, and .nt serializations of the model.
[test.zip](https://github.com/crapo/sadlos2/files/314045/test.zip)
