### ISSUE TITLE
Detect ambiguous unqualified names

### ISSUE THREAD

**Issue by GEGlobalResearch** [crapo/sadlos2#96]
Suppose Model A defines concept Foo (a:Foo) and Model B defines concept Foo (b:Foo) and Model C imports A and B. If the author now writes an expression containing unqualified name "Foo", the Xtext parser/linker will silently choose a:Foo or b:Foo and no error will be detected. The desired behavior is to create an "ambiguous name" error marker with quick fix menu "a:Foo" and "b:Foo".

**Comment by crapo** [comment]
I've added a test, testLinkingAmbiguousElementsBigger, to ValidationTest.xtend. Currently the test passes because it is checking for the issue message that is generated, but there should not be any issue as there is no duplication. In our test and real projects this generates almost continuous error markers on every line.

**Comment by crapo** [comment]
This seems to work correctly now.
